ask commit cf0f596ad71dda7e4cf00338d91b6a882a11d354
ask evaluate [App [Lam [Var [Z]]] [Lam [Var [Z]]]]
wait
ask {$1 [Nil] [Done]}
wait
view $1
ask {$2 $4 [Arg $3 $4 $5]}
wait
view $4
ask {$5 $6 [Fun [Closure $2 $3] $7]}
wait
view $5
ask {$6 [Cons [Closure $2 $3] $7] $8}
wait
ask lookup $2 $3
wait
view $1
view $2
reply $3
ask {[Lam $6] $7 $4}
wait
reply Closure $2 $3
reply $8
reply $9
reply $8
reply $6
reply $2
ask evaluate [App [App [Lam [Lam [Var [S [Z]]]]] [Lam [Var [Z]]]] [Lam [Var [Z]]]]
wait
view $3
ask lookup $2 $5
wait
reply $6
ask evaluate [App [App [Lam [Lam [App [Var [Z]] [Var [S [Z]]]]]] [Lam [Lam [App [Var [S [Z]]] [App [Var [S [Z]]] [Var [Z]]]]]]] [Lam [Lam [App [Var [S [Z]]] [App [Var [S [Z]]] [App [Var [S [Z]]] [Var [Z]]]]]]]]
wait
reply $7
